INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (32, 'Menjelaskan trik trik jitu dalam belajar bahasa pemrograman Java.', 35);
INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (33, 'Menggali Tujuan yang pasti dari diri kita.', 36);
INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (34, 'Menjelaskan trik trik jitu dalam belajar Photoshop.', 37);
INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (35, 'Menjelaskan trik trik jitu dalam belajar bahasa pemrograman PHP.', 38);
INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (36, 'Menjelaskan rumus-rumus dan trik perkalian kuadrat.', 39);
INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (37, 'Menjelaskan belajar matematika itu mudah.', 40);
INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (38, 'Tutorial belajar berenang.', 41);
INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (39, 'Trik-trik yang dapat dipelajari di sepakbola.', 42);
INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (40, 'Menjelaskan dasar-dasar belajar C# yang menyenangkan.', 43);
INSERT INTO `deskripsi`(`id_deskripsi`, `isi`, `id_buku`) VALUES (41, 'Menjelaskan dasar-dasar HTML untuk pemula.', 44);