INSERT INTO `deskripsi` VALUES (1, '10 Langkah Memaksimalkan Potensi Diri', 2);
INSERT INTO `deskripsi` VALUES (2, 'Membuat aplikasi website berteknologi Ajax dan AntiXSS; Berbagai contoh aplikasi website dari yang paling sederhana hingga yang rumit', 3);
INSERT INTO `deskripsi` VALUES (3, 'Catatan mahasiswa gokil', 4);
INSERT INTO `deskripsi` VALUES (4, 'Duel cowok ngomongin cintrong', 5);
INSERT INTO `deskripsi` VALUES (5, 'Informasi Teknis, Interface, Dasar-dasar video editing, video transition, video effect, titling, dan export project', 7);
INSERT INTO `deskripsi` VALUES (6, 'Teknik berbicara yang membawa anda ke jenjang sukses', 9);
INSERT INTO `deskripsi` VALUES (7, 'Buku ini digunakan sebagai dasar dalam pembelajaran Ilmu Komputer. Karena teknik informatika selalu memerlukan wawasan tentang matematika diskrit', 10);
INSERT INTO `deskripsi` VALUES (8, 'Novel ini menceritakan kisah Milea, siswa pindahaan dari Jakarta yang bertemu Dilan di SMA barunya di Bandung. Dengan latar waktu tahun 1990, cerita ini punya modal positif untuk menonjol di tengah generasi remaja masa kini (meski bukan itu yang jadi poin utama Pidi Baiq menulis cerita ini).', 11);
INSERT INTO `deskripsi` VALUES (9, 'Cerita tentang Dika. Selepas SMU, Dika (Raditya Dika), yang mempunyai nama panggilan Kambing, harus melanjutkan pendidikan di Adelaide, Australia. Ketika dia menjalani kuliah di Australia,', 12);
INSERT INTO `deskripsi` VALUES (10, 'Berisikan tentang 7 kebiasaan yang dapat kita lakukan untuk menjadi orang dengan tingkat efektivitas yang tinggi.', 13);
INSERT INTO `deskripsi` VALUES (11, 'Memberikan Pengetahuan tentang rumus-rumus dasar dalam pembelajaran Fisika', 14);
INSERT INTO `deskripsi` VALUES (12, 'Kisah tentang Bujang yang meceritakan kisah hidupnya', 15);
INSERT INTO `deskripsi` VALUES (13, 'Bercerita tentang pengalamannya belajar hidup dari apa yang dia cintai, sambil menemukan hal remeh untuk ditertawakan di sepanjang perjalanan.', 16);
INSERT INTO `deskripsi` VALUES (14, 'Buku ini digunakan sebagai cara penggunaan photography yang ada pada sebuah smartphone', 17);
INSERT INTO `deskripsi` VALUES (15, 'Memberikan prinsip serta masukan bagi pembaca dalam menempuh jalan hingga sukses', 18);
INSERT INTO `deskripsi` VALUES (16, 'Buku ini tentang pembelajaran astronomi tentang pengenalan atmosfer yang terdapat pada bumi', 19);
INSERT INTO `deskripsi` VALUES (17, 'Buku pembelajaran dalam konsep biologi yang mempelajari transformasi yang terjadi pada tumbuhan', 20);
INSERT INTO `deskripsi` VALUES (18, 'Novel ini mengisahkan kehidupan Fahri, tokoh utama, yang diwarnai dengan kisah hubungan lelaki dengan perempuan. Fahri adalah seorang mahasiswa Indonesia yang kuliah di Universitas Al Azhar, Mesir. Ia selalu berusaha meneladani Rasulullah Saw', 21);
INSERT INTO `deskripsi` VALUES (22, 'Menjelaskan trik trik jitu dalam belajar bahasa pemrograman PHP.', 25);
INSERT INTO `deskripsi` VALUES (23, 'Menggali potensi yang ada dalam diri kita.', 26);
INSERT INTO `deskripsi` VALUES (24, 'Menjelaskan trik trik jitu dalam belajar Corel.', 27);
INSERT INTO `deskripsi` VALUES (25, 'Menjelaskan trik trik jitu dalam belajar bahasa pemrograman Java.', 28);
INSERT INTO `deskripsi` VALUES (26, 'Tutorial menanam jagung di Pot Rumah.', 29);
INSERT INTO `deskripsi` VALUES (27, 'Trik supaya mudah menangkap ikan tanpa melukainya.', 30);
INSERT INTO `deskripsi` VALUES (28, 'Belajar macam macam hewan.', 31);
INSERT INTO `deskripsi` VALUES (29, 'Menjelaskan penjelasan tentang kuda Poni.', 32);
INSERT INTO `deskripsi` VALUES (30, 'Berisi tentang penjelasan framework MVC di Java.', 33);
INSERT INTO `deskripsi` VALUES (31, 'Menjelaskan tentang cara menghias aplikasi di java dengan javafx.', 34);
INSERT INTO `deskripsi` VALUES (32, 'Menjelaskan trik trik jitu dalam belajar bahasa pemrograman Java.', 35);
INSERT INTO `deskripsi` VALUES (33, 'Menggali Tujuan yang pasti dari diri kita.', 36);
INSERT INTO `deskripsi` VALUES (34, 'Menjelaskan trik trik jitu dalam belajar Photoshop.', 37);
INSERT INTO `deskripsi` VALUES (35, 'Menjelaskan trik trik jitu dalam belajar bahasa pemrograman PHP.', 38);
INSERT INTO `deskripsi` VALUES (36, 'Menjelaskan rumus-rumus dan trik perkalian kuadrat.', 39);
INSERT INTO `deskripsi` VALUES (37, 'Menjelaskan belajar matematika itu mudah.', 40);
INSERT INTO `deskripsi` VALUES (38, 'Tutorial belajar berenang.', 41);
INSERT INTO `deskripsi` VALUES (39, 'Trik-trik yang dapat dipelajari di sepakbola.', 42);
INSERT INTO `deskripsi` VALUES (40, 'Menjelaskan dasar-dasar belajar C# yang menyenangkan.', 43);
INSERT INTO `deskripsi` VALUES (41, 'Menjelaskan dasar-dasar HTML untuk pemula.', 44);
